### ISSUE TITLE
Unknown miio device found

### ISSUE THREAD

**Issue by Notrial** [rytilahti/python-miio#204] opened 2018-02-06 16:29 UTC
Hi guys,

I'm getting continous warnings (below) every 30 mins or so for both of my Yeelight Ceiling Lamps. I also have Yeelight desk lamp and bunch of bulbs / strips and they don't give any warnings.
I have to point out that despite the warnings the lights seem to work fine. It's just annoying to see the warnings in Home Assistant log all the time (I'm on 0.62.1...Hass.io).

`Unknown miio device found: ServiceInfo(type='_miio._udp.local.', name='yeelink-light-ceiling1_mibt77535239._miio._udp.local.', address=b'\xc0\xa8\x01#', port=54321, weight=0, priority=0, server='yeelink-light-ceiling1_mibt77535239.local.', properties={b'epoch': b'1', b'mac': b'7811dca8d7be'})`

**Comment by rytilahti** [comment] 2018-02-06 19:09
This is caused by netdisco, not this library. The fix is already in so I'm closing this: https://github.com/home-assistant/netdisco/pull/168

**Closed by rytilahti** 2018-02-06 19:09 UTC

**Comment by Notrial** [comment] 2018-02-12 08:14
Hi, 
Sorry for being a pest, but I've updated to 0.63 and this problem seems to be present still. I'm new to HA, so I'm unfamiliar with component updates and whether the fixes are applied automatically with the next HA build?

**Comment by pauln** [comment] 2018-02-12 09:16
@Notrial There hasn't yet been a release of `netdisco` since the pull request was merged, so it didn't make it into 0.63.  When it's released and Home Assistant is updated to use it, you won't have to do anything other than update Home Assistant.

**Comment by Notrial** [comment] 2018-02-26 08:45
I'm on 0.64 now and Yeelight Celing lamps still report as "Unknown miio device found", all three of them.

**Comment by pauln** [comment] 2018-02-26 11:24
There still hasn't been a new release of [`netdisco`](https://github.com/home-assistant/netdisco), so unfortunately Home Assistant 0.64 can't/doesn't include the update.

I don't know if there's any kind of update policy which might suggest when a new version of `netdisco` should be released / added to Home Assistant.  Perhaps you could try opening an issue on the `netdisco` repo to ask about the update policy (or even to ask nicely for an update to be released / pushed to Home Assistant)?

**Comment by Notrial** [comment] 2018-02-26 11:35
@pauln I will try to do that, thanks!
