### ISSUE TITLE
Found an unsupported model 'zhimi.fan.za5' for class 'FanZA5 ,and 'user ack timeout

### ISSUE THREAD

**Issue by Tinuz97** [rytilahti/python-miio#1350] opened 2022-03-07 21:38 UTC
**Describe the bug**
Updated to the latest Home Assistant (2022.3.2), the issue started (worked fine before with 2022.2.9). 
Also installed the latest version of miio (
2022.3.0), that got updated for the latest Home Assistant. 

I have the Xiaomi SmartMi Xiaomi SmartMi Standing Fan 3.
Removed the addon, installed again (tryed both options, manual with ip adress and the Token) and the 'standard' option. Used DE as server (worked fine before), but Home Assitant is reporting this in the log:
PS: if i revert back to Home assitant 2022.2.9 it just works fine.....

Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:155
First occurred: 22:25:23 (13 occurrences)
Last logged: 22:35:05

Found an unsupported model 'zhimi.fan.za5' for class 'FanZA5'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

And this error:

Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 22:25:32 (2 occurrences)
Last logged: 22:28:58

Config entry 'Ventilator' for xiaomi_miio integration not ready yet: {'code': -9999, 'message': 'user ack timeout'}; Retrying in background

**Version information (please complete the following information):**
 - OS: haos_rpi4-64-7.4
 - python-miio: tryed both commands, did not work for me (using latest version miio that got updated for the new home assistant )

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1

**Expected behavior**
A clear and concise description of what you expected to happen

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag

**Comment by Tinuz97** [comment] 2022-03-07 21:40
I have this in the YAML:

# Xiaomi Ventilator
fan:
    - platform: xiaomi_miio_fan
      name: Xiaomi Smart Fan
      model: zhimi.fan.za5
      host: 192.168.1.199
      token: !secret token

**Comment by rytilahti** [comment] 2022-03-07 22:11
Duplicate of #1344, fixed already in the master branch and I'll prepare a new release tonight.

**Closed by rytilahti** 2022-03-07 22:11 UTC
Labels: bug, duplicate

**Comment by Tinuz97** [comment] 2022-03-07 22:12
> Duplicate of #1344, fixed already in the master branch and I'll prepare a new release tonight.

OH sorry, did not see that one, but thank you.

**Comment by Tinuz97** [comment] 2022-03-08 10:44
@rytilahti 

Now i get this at the check config (check the YAML)

Platform error fan.xiaomi_miio_fan - cannot import name 'FanP9' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

But the fan is working fine,only can't reboot Home Assistant now.
I have the sane in the YAML (changed nothing):

# Xiaomi Ventilator
fan:
    - platform: xiaomi_miio_fan
      name: Xiaomi Smart Fan
      model: zhimi.fan.za5
      host: 192.168.1.199
      token: !secret token 

![image](https://user-images.githubusercontent.com/47715606/157222486-5d9e3c37-5dca-4ac6-8698-d9db70ebce8c.png)

**Comment by Tinuz97** [comment] 2022-03-08 10:47
And found this in the log:

Logger: homeassistant.config
Source: custom_components/xiaomi_miio_fan/fan.py:36
Integration: xiaomi_miio_fan ([documentation](https://github.com/syssi/xiaomi_fan), [issues](https://github.com/syssi/xiaomi_fan/issues))
First occurred: 11:28:10 (1 occurrences)
Last logged: 11:28:10

Platform error: fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 36, in <module>
    from miio import (  # pylint: disable=import-error
ImportError: cannot import name 'FanP9' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

**Comment by Tinuz97** [comment] 2022-03-08 16:43
Nevermind, this update fixed it. 
![Screenshot_20220308-174248](https://user-images.githubusercontent.com/47715606/157284400-c3c37f6d-e54d-4f98-a68d-631e2ef20bb8.jpg)
