### ISSUE TITLE
[ADD] Xiaomi Mijia Caméra IP WiFi 1080P Panoramique

### ISSUE THREAD

**Issue by BedoM** [rytilahti/python-miio#484] opened 2019-02-22 13:25 UTC
Add Xiaomi Mijia Caméra IP WiFi 1080P 360° Panoramique 

Control, view, stream and other functions !

**Comment by rytilahti** [comment] 2019-02-22 13:53
Is this a duplicate of #429 or #373?

**Comment by BedoM** [comment] 2019-02-23 11:29
This is not the subject 429 nor the 373.

Here is the gearbest link: https://fr.gearbest.com/ip-cameras/pp_009991451325.html?wid=1433363

And here is the discover:
--------------------------------------------------------------------------------------------------------
root@DEBIAN-DEV:/# miio discover
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 76331731
Model info: Unknown
Address: 192.168.1.35
Token: ???
Support: Unknown

Device ID: 122590752
Model info: Unknown
Address: 192.168.1.39
Token: ???
Support: Unknown

Device ID: 96613887
Model info: Unknown
Address: 192.168.1.24 
Token: ???
Support: Unknown
________________________________________________________________________________________________________


--------------------------------------------------------------------------------------------------------
I have 2 cameras of the same type and a vacuum cleaner v2 and in wireshark i have this token 21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
21310020ffffffffffffffffffffffffffffffffffffffffffffffffffffffff

......

**Comment by impankratov** [comment] 2019-08-20 20:45
@rytilahti @BedoM
That camera was added in this PR.
https://github.com/rytilahti/python-miio/pull/516

Only basic functionality though, I don't know if there's any way to stream a video off of it.

**Comment by rytilahti** [comment] 2020-02-08 13:18
Some information how the streaming works on another device can be found at https://github.com/rytilahti/python-miio/issues/373#issuecomment-427606838 . Maybe this camera functions similarly?

**Closed by rytilahti** 2020-02-08 13:18 UTC
