### ISSUE TITLE
Xiao AI Smart Alarm Clock Time

### ISSUE THREAD

**Issue by Koponyeges** [rytilahti/python-miio#600] opened 2019-12-15 18:56 UTC
Hi. How do I change the time? Please help

miiocli device --ip xxx.xxx.xxx.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxx info
Model: zimi.clock.myk01
Hardware version: Linux
Firmware version: 3.5.7_0034
Network: {'localIp': '192.168.xxx.xxx', 'mask': '255.255.255.0', 'gw': '192.168.xxx.xxx}
AP: {'ssid': 'xxxxxxxx', 'bssid': 'xx:xx:xx:xx:xx', 'rssi': -42, 'freq': 2437}

zimi-clock-myk01_mibtD166 , AI01ZM

**Comment by syssi** [comment] 2019-12-15 19:12
Duplicate of #599

**Closed by syssi** 2019-12-15 19:12 UTC
