### ISSUE TITLE
ijai.vacuum.v10 unsupported device

### ISSUE THREAD

**Issue by kramzyukdenis** [rytilahti/python-miio#1335] opened 2022-02-26 14:56 UTC
**Device information:**

  - Name(s) of the device: Mi Robot Vacuum-Mop 2 Lite
  - Link:

  - Model: ijai.vacuum.v10
  - Hardware version: esp32
  - Firmware version: 2.1.7_0038

**Comment by danyvega1990** [comment] 2022-04-05 22:47
Is this issue dead or someone is working on it?

**Comment by rytilahti** [comment] 2022-04-05 23:34
This is an open source project without any affiliation to xiaomi nor any of the product vendors, I suppose I should update the readme to make it clear... :-)

So, assuming that no one has indicated here that they are working on it, I doubt someone is working on it currently.

**Comment by danyvega1990** [comment] 2022-04-06 01:49
Sad, somehow I was expecting it tho

**Comment by rytilahti** [comment] 2022-08-15 18:51
Duplicate of #1319

**Closed by rytilahti** 2022-08-15 18:51 UTC
Labels: new device
