### ISSUE TITLE
Add support for Xiao AI Smart Alarm Clock

### ISSUE THREAD

**Issue by auredor** [rytilahti/python-miio#538] opened 2019-08-06 11:13 UTC
model : Xiaomi XiaoAI Smart Alarm Clock

Features : 
- set / get clock
- set / get alarm value
- enable / disable alarm
- dim clock light ?

https://ko.aliexpress.com/item/33025242986.html?spm=a2g0o.productlist.0.0.31312e2fIBpcuy&algo_pvid=856a315f-1575-422a-bec4-848a3e339959&algo_expid=856a315f-1575-422a-bec4-848a3e339959-4&btsid=f758c0cd-96eb-4374-94eb-e113b43608c6&ws_ab_test=searchweb0_0,searchweb201602_7,searchweb201603_60

And get it available for HA.

Many thanks

**Comment by rytilahti** [comment] 2019-08-08 03:02
This is a duplicate of #505, so I'll close this in favor of it.

**Closed by rytilahti** 2019-08-08 03:02 UTC
