### ISSUE TITLE
chuangmi.plug.212a01

### ISSUE THREAD

**Issue by ssarioglu** [rytilahti/python-miio#948] opened 2021-02-14 09:37 UTC
**Device information:**
Xioami Wireless Switch New Model 

  - Model: [chuangmi.plug.212a01]

**Comment by starkillerOG** [comment] 2021-02-20 10:28
see also: https://github.com/rytilahti/python-miio/issues/844

**Comment by ha0y** [comment] 2021-05-17 07:25
The device is currently not supported by python-miio, but you can use it in Home Assistant with the following integration:
https://github.com/ha0y/xiaomi_miot_raw
(You can install it directly from HACS)

![212a01](https://user-images.githubusercontent.com/30557072/118448042-0ecdb500-b724-11eb-839b-c109513c9783.png)

**Comment by rytilahti** [comment] 2022-01-10 16:54
Duplicate of #844.

**Closed by rytilahti** 2022-01-10 16:54 UTC
Labels: new device
