### ISSUE TITLE
Can't retrieve token from Android app

### ISSUE THREAD

**Issue by ianloic** [rytilahti/python-miio#246] opened 2018-03-05 01:03 UTC
I just got a _Roborock S5_, set it up with _Mi Home_ version 5.1.5. I tried extracting the token from a backup of the app but didn't get anything. When I take a look at the sqlite database the token column looks empty:
```
sqlite> select localIP, token,name,model from devicerecord;
localIP        token       name             model             
-------------  ----------  ---------------  ------------------
192.168.86.35              Roborock Vacuum  roborock.vacuum.s5
```

**Comment by rytilahti** [comment] 2018-03-05 06:08
This is a duplicate of #185, the simplest option currently is to downgrade and use an older version of the app for extracting the token (you can update the app back afterwards if you like).

**Closed by rytilahti** 2018-03-05 06:08 UTC

**Comment by jtitley** [comment] 2018-03-22 17:46
I tried the downgrade trick but it is still empty. I installed the apk from the link.
