### ISSUE TITLE
Xiaomi WiFi Power Plug(Bluetooth Gateway)(chuangmi.plug.hmi208)

### ISSUE THREAD

**Issue by XingKongSync** [rytilahti/python-miio#840] opened 2020-10-21 13:45 UTC
**Device information:**

  - Name(s) of the device: Xiaomi WiFi Power Plug(Bluetooth Gateway)
  - Link: [Store Link](https://union-click.jd.com/jdc?e=&p=AyIGZRprFQMTBlUaXBcBGw9cKx9KWkxYZUIeUENQDEsFA1BWThgOTkRHXE4ZVRpaFAITAFcYUh0LDV4QRwYlAwhjJn1fT1dwWA1NI0NpcUFRQgcdRB4LZRhcHAsUN1YZXBcEFgJWHGtfEWZSDV4FVhEZFIKt%2BMO%2FiBQZK1sWMkRpVRpaFAMTAlUYWSUCEQBRGV4dAxoPZRtfEwUXAFAZXBIDFgVlG1MSMk5FB1oZJTIiBGUraxUyEjcKXwZIMhAGVBlZ)

Use `miiocli device --ip <ip address> --token <token> info`.

- Model: chuangmi.plug.hmi208
- Hardware version: esp32
- Firmware version: 2.0.6_0025

**Comment by rytilahti** [comment] 2020-10-24 23:43
This is a duplicate of #616.

**Closed by rytilahti** 2020-10-24 23:43 UTC
Labels: new device
