### ISSUE TITLE
HA 2021.12.x Xiaomi Philips Zhirui downlights not working after updating HA

### ISSUE THREAD

**Issue by XLR-24** [rytilahti/python-miio#1248] opened 2021-12-14 00:09 UTC
Till version 2021.11.5 everything was normal working with the Xiaomi Philips Zhirui downlights, after updating to the last version they are not any more connected and reachable in HA. I can reach them with the native Xiaomi app.

Got the following Log details in HA:
------------------------------------------------------------------------------------------------------------------------
Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: December 13, 2021, 23:06:27 (36 occurrences)
Last logged: 24:06:02

Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

--------------------------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.light
Source: components/xiaomi_miio/light.py:521
Integration: Light (documentation, issues)
First occurred: December 13, 2021, 23:06:27 (33 occurrences)
Last logged: December 13, 2021, 23:06:29

xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 502, in async_update
    self._color_temp = self.translate(
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 521, in translate
    value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by woody-ru** [comment] 2021-12-14 00:13
Same story with me
Also has warning: 
```
 Logger: miio.device
Source: /usr/local/lib/python3.9/site-packages/miio/device.py:153
First occurred: 2:46:55 AM (10 occurrences)
Last logged: 2:46:55 AM

    Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
    Found an unsupported model 'philips.light.ceiling' for class 'Ceil'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

```

**Comment by woody-ru** [comment] 2021-12-14 00:18
Seem like ugly typo:
https://github.com/rytilahti/python-miio/blob/d82121cff9ad019d18e57f0e732ed849d7f3469f/miio/philips_bulb.py#L139

**Comment by rytilahti** [comment] 2021-12-14 01:35
This is being tracked here https://github.com/home-assistant/core/issues/61523 - as #1237 is merged to python-miio, it should work as soon as a new release is done, but I'm hesitant to make a release before getting some input that it's really fixed with that.

**Comment by XLR-24** [comment] 2021-12-14 05:28
How can I help/test?

**Comment by lightzhuk** [comment] 2021-12-14 06:22
I will also gladly join for testing.  because I am experiencing this problem too.

**Comment by jjanderson** [comment] 2021-12-14 09:46
also happy to test

**Comment by Kirmas** [comment] 2021-12-14 11:10
I also can help with test. But currently I dont understand how I can change python-miio in home assistant docker container to check this. @rytilahti Could you provide some instruction?

**Comment by lolouk44** [comment] 2021-12-14 13:46
I can confirm that for Philips Bulb the issue is resolved with the latest merge.

**Comment by rytilahti** [comment] 2021-12-14 16:21
Thanks for testing @lolouk44! I'll prepare a new release asap (later tonight).

@XLR-24 @lightzhuk @jjanderson @Kirmas it should be enough for testing to replace the `philips_bulb.py` inside your installation with the one from python-miio master, but as it's been confirmed to work there is no need to figure out how to do that.

**Comment by lightzhuk** [comment] 2021-12-14 16:57
i can't figure out where should i replace the file?  Can you help me?  hone assistant OS installation

**Comment by lolouk44** [comment] 2021-12-14 17:01
`find / -name "philips_bulb.py"` will give you the location of the file.
Replace the file name with the one you need to update of course

**Comment by Kirmas** [comment] 2021-12-14 17:21
Can confirm that this work for all my Xiaomi Philips Zhirui.

**Comment by lolouk44** [comment] 2021-12-14 18:56
I can only confirm it works for my Xiaomi Philips Zhirui Candle Light as that's the only Xiaomi Philips light that I have.
It's a quick test for you to do and confirm...

**Comment by Dasisfakt** [comment] 2021-12-14 19:02
Friends, I'm from Russia waiting for the problem to be fixed, half of the house is not working. I don't know how to replace files on my own to check. (I work through a translator)

**Comment by lolouk44** [comment] 2021-12-14 19:03
See above:


> `find / -name "philips_bulb.py"` will give you the location of the file.
> Replace the file name with the one you need to update of course

or downgrade to 2012.11.5

**Comment by lolouk44** [comment] 2021-12-14 19:34
> Is this work for raspberry pi HASS OS installation?

probably not. If it's that critical, downgrade to 2021.11.5

**Comment by lightzhuk** [comment] 2021-12-14 20:10
Sorry, but I don't know how to find the file you want to replace on my system.  returned to the previous version.  Thank you.

**Comment by rytilahti** [comment] 2021-12-14 21:09
I'm closing this now as there's a homeassistant PR to fix this for good: https://github.com/home-assistant/core/pull/61831 - I'm terribly sorry for the inconvenience caused by these regressions :-(

**Closed by rytilahti** 2021-12-14 21:09 UTC
