### ISSUE TITLE
Unsupported model ijai.vacuum.v3

### ISSUE THREAD

**Issue by antoweb** [rytilahti/python-miio#1388] opened 2022-04-08 15:07 UTC
**Describe the bug**
I have  a xiaomi vacuum model mop 2 pro. Launching the command following:

miiocli viomivacuum --ip 192.168.1.100 --token MY_TOKEN get_rooms

Got an error:
WARNING:miio.device:Found an unsupported model 'ijai.vacuum.v3' for class 'ViomiVacuum'

**Version information (please complete the following information):**
 - OS: Raspbian
 - python-miio: miiocli, version 0.5.11

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: mop 2 pro (ijai.vacuum.v3)
  - Hardware version: 
  - Firmware version: 4.3.3_0048

**To Reproduce**
1.

**Expected behavior**

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

**Comment by rytilahti** [comment] 2022-04-11 04:09
Are other viomivacuum commands working just fine on that device? If not, this is a duplicate of #1385. There is currently no support for any ijai devices in the lib, contributions are welcome as always!

**Comment by antoweb** [comment] 2022-06-02 07:11
Yes the following command works but with warning:

root@raspberrytv:/home/pi# miiocli viomivacuum --ip 192.168.1.100 --token MY_TOKEN get_maps
Running command get_maps
WARNING:miio.device:Found an unsupported model 'ijai.vacuum.v3' for class 'ViomiVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
{'out': [{'piid': 4, 'value': '[{"name":"Filomena","id":MAP-ID,"cur":false},{"name":"Mappa1","id":1654083172,"cur":true}]'}], 'code': 0}

**Comment by antoweb** [comment] 2022-06-02 07:19
Also consumable_status works with warning

root@raspberrytv:/home/pi# miiocli viomivacuum --ip 192.168.1.100 --token MY-TOKEN consumable_status
Running command consumable_status
WARNING:miio.device:Found an unsupported model 'ijai.vacuum.v3' for class 'ViomiVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
<ViomiConsumableStatus filter=1 day, 14:00:00 filter_left=5 days, 22:00:00 main_brush=1 day, 14:00:00 main_brush_left=13 days, 10:00:00 mop=1 day, 14:00:00 mop_left=5 days, 22:00:00 sensor_dirty=0:00:00 sensor_dirty_left=0:00:00 side_brush=1 day, 14:00:00 side_brush_left=5 days, 22:00:00>

**Comment by jeffrey-zammit** [comment] 2022-08-22 12:08
Was there ever any update to this?

**Comment by rytilahti** [comment] 2022-09-06 23:02
Closing as duplicate of #1385 - @jeffrey-zammit see (and subscribe to) the linked PR for the status.

**Closed by rytilahti** 2022-09-06 23:02 UTC
Labels: bug
