### ISSUE TITLE
AirHumidifier2 error in Domoticz

### ISSUE THREAD

**Issue by zzaal** [rytilahti/python-miio#991] opened 2021-03-25 19:19 UTC
After updating 0.5.4. to version 0.5.5.2, the Airhumidifer2 device in the Domoticz system receives an error when initializing the device:
Error: dictionary update sequence element #0 has length 21; 2 is required

The device is controlled, but the on/off status does not change in Domoticz

After rolling back to version 0.5.4. everything works correctly

 OS: Raspbian GNU/Linux 10 (buster)
 python-miio: 0.5.5.2

Model: zhimi.humidifier.ca1
Hardware version: MTK7697
Firmware version: 2.0.9

**Comment by rytilahti** [comment] 2021-04-08 14:54
More information is needed, is the `miiocli` working fine for the device? Could this be an issue on how domoticz interacts with this library?

**Comment by zzaal** [comment] 2021-04-08 15:34
i use plugin in domoticz: https://github.com/develop-dvs/domoticz-AirHumidifier2
with 0.5.5.2 in Domoticz log i have plugin initialization with error: 
Error: dictionary update sequence element #0 has length 21; 2 is required
miiocli is working fine in terminal, but with plugin in Domoticz no actions work
i can not on/off and status not change.

**Comment by rytilahti** [comment] 2021-04-08 16:10
Please report it to the developer of that plugin and/or try to find out how to get a full length stacktrace for that error, but it sounds like this is a problem in that plugin instead of in this library.

**Comment by zzaal** [comment] 2021-04-08 16:17
ok.
But with 0.5.4. all work fine in Domoticz.

**Comment by rytilahti** [comment] 2021-04-08 16:21
Well, that's why it'd be great to have a full stacktrace to see what exactly the plugin is doing and why it is now broken. There were some changes to status containers (#941) among other things (all changes listed in https://github.com/rytilahti/python-miio/releases/tag/0.5.5), but as long as the plugin doesn't parse `__repr__` that shouldn't be the cause for this.

**Comment by zzaal** [comment] 2021-04-08 16:47
THX
I wrote to the developer too

**Comment by DAVIZINH0** [comment] 2021-04-09 06:22
i have the same problem, and open a issue in the developer of the plugin for domoticz but not reply :-(
I will try to obtain more log info this weekend and  posit.

i dont know how to test the humidifier with console comands :-( with other devices are easy to me. @zzaal can you say to me the comands you use? thanks!

**Comment by zzaal** [comment] 2021-04-09 06:57
> @zzaal can you say to me the comands you use? thanks!

you need to know the: model, ip, token.
my Airhumidifier2 is
model: ca1
ip address: 192.168.0.33
token: f3d9ddfef76c76c6ec2ef0cd7fc09a79

the command line looks like:

`miiocli airhumidifierca1 --ip 192.168.0.33 --token f3d9ddfef76c76c6ec2ef0cd7fc09a79 status`

this command displays the status of the humidifier

instead of the "**status**" command, you can use other commands:
**info**                           Get miIO protocol information from the device.
**off**                             Power off.
**on**                             Power on.
**raw_command**          Send a raw command to the device.
**set_buzzer**                 Set buzzer on/off.
**set_child_lock**            Set child lock on/off.
**set_dry**                       Set dry mode on/off.
**set_led**                       Turn led on/off.
**set_led_brightness**     Set led brightness.
**set_mode**                   Set mode.
**set_target_humidity**   Set the target humidity.
**status**                         Retrieve properties.

for example, the shutdown command will look like this:
`miiocli airhumidifierca1 --ip 192.168.0.33 --token f3d9ddfef76c76c6ec2ef0cd7fc09a79 off`

**Comment by DAVIZINH0** [comment] 2021-04-09 06:59
pefect, thanks a lot!!.
I will make some test this weekeend and try to obtain some log in the domoticz.
The developer of the plugin is missing :-(
we will try to find some more info

**Comment by DAVIZINH0** [comment] 2021-04-10 17:23
I try to expand the log of the plugin and imposible. dont obtain more information :-(

**Comment by develop-dvs** [comment] 2022-01-06 13:10
>i use plugin in domoticz: https://github.com/develop-dvs/domoticz-AirHumidifier2
>The developer of the plugin is missing :-(
i'm here) just need replay error, but i cant. all work fine

**Comment by develop-dvs** [comment] 2022-01-06 19:19
fix! update miio and [plugin from repo](https://github.com/develop-dvs/domoticz-AirHumidifier2)

**Comment by rytilahti** [comment] 2022-01-08 01:24
Thanks for the update! I'll close this issue now, as it's not really related to this project :-)

**Closed by rytilahti** 2022-01-08 01:24 UTC
Labels: bug
