### ISSUE TITLE
Dreame P2008

### ISSUE THREAD

**Issue by ThibaultMoka** [rytilahti/python-miio#1187] opened 2021-11-22 18:45 UTC
**Device information:**

  - Name(s) of the device: dreame-vacuum-p2008 (Commercial name Dreame D9)

** Additional infos **

Hello,
First, i would like to thank you for helping us. 
When I tried to connect my Dreame vacuum, i get this message : 

![Capture d’écran 2021-11-22 à 19 37 30](https://user-images.githubusercontent.com/94802340/142917451-89a42a49-a61e-4fe5-b387-1e0c0da3cfc8.png)

Every command I tried got me "No response from the device" info.

Can you please help me ? 

Thank you,
Thibault

**Comment by rytilahti** [comment] 2022-01-10 17:33
Duplicate of #812

**Closed by rytilahti** 2022-01-10 17:33 UTC
Labels: new device
