### ISSUE TITLE
not supported chuangmi.plug.hmi208

### ISSUE THREAD

**Issue by AlexQuaken** [rytilahti/python-miio#691] opened 2020-05-04 06:54 UTC
not supported chuangmi.plug.hmi208 the new smart switch from Xiaomi with two USB ports and bt gateway function.

**Comment by rytilahti** [comment] 2020-05-06 14:22
Could you try out which of the following works:
* `miiocli device raw_command get_prop ["on", "usb_on", "temperature"]`
* `miiocli device raw_command get_prop ["power", "temperature"]`
* `miiocli device raw_command get_prop ["power", "usb_on", "temperature"]`
* `miiocli device raw_command get_prop ["all"]`

You could also simply modify `miio/chuangmi_plug.py` to add that hmi208 after hmi206 and experiment using `miiocli chuangmiplug` to see which commands work as expected.

**Comment by rytilahti** [comment] 2020-05-06 22:54
This is a duplicate of #616, feel free to add your findings on that issue!

**Closed by rytilahti** 2020-05-06 22:54 UTC
Labels: new device

**Comment by AlexQuaken** [comment] 2020-05-07 16:21
```
MODEL_CHUANGMI_PLUG_V3 = "chuangmi.plug.v3"
MODEL_CHUANGMI_PLUG_V1 = "chuangmi.plug.v1"
MODEL_CHUANGMI_PLUG_M1 = "chuangmi.plug.m1"
MODEL_CHUANGMI_PLUG_M3 = "chuangmi.plug.m3"
MODEL_CHUANGMI_PLUG_V2 = "chuangmi.plug.v2"
MODEL_CHUANGMI_PLUG_HMI205 = "chuangmi.plug.hmi205"
MODEL_CHUANGMI_PLUG_HMI206 = "chuangmi.plug.hmi206"
MODEL_CHUANGMI_PLUG_HMI208 = "chuangmi.plug.hmi208"

AVAILABLE_PROPERTIES = {
    MODEL_CHUANGMI_PLUG_V1: ["on", "usb_on", "temperature"],
    MODEL_CHUANGMI_PLUG_V3: ["on", "usb_on", "temperature", "wifi_led"],
    MODEL_CHUANGMI_PLUG_M1: ["power", "temperature"],
    MODEL_CHUANGMI_PLUG_M3: ["power", "temperature"],
    MODEL_CHUANGMI_PLUG_V2: ["power", "temperature"],
    MODEL_CHUANGMI_PLUG_HMI205: ["power", "temperature"],
    MODEL_CHUANGMI_PLUG_HMI206: ["power", "temperature"],
    MODEL_CHUANGMI_PLUG_HMI208: ["power", "temperature"],
}

```

Make changes as that, then copy to hassio by run command "docker cp /usr/share/hassio/homeassistant/chuangmi_plug.py homeassistant:/usr/local/lib/python3.7/site-packages/miio/chuangmi_plug.py" after that all my smart sockets makes inactive

lots of errors on all my smartsockets ip adresses
Unable to discover a device at address 192.168.0.79
19:18:33 – /usr/local/lib/python3.7/site-packages/miio/miioprotocol.py (ERROR) - первое сообщение получено 19:13:23 и повторялось 17 раз

somethig was wrong, after restore file from backup, error still not fix, mb i need do chmod + ?
