### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by bennychee** [rytilahti/python-miio#385] opened 2018-10-04 05:43 UTC
When running miio-extract-tokens, i get the following error:

```
# miio-extract-tokens backup.ab
Traceback (most recent call last):
  File "/usr/local/bin/miio-extract-tokens", line 7, in <module>
    from miio.extract_tokens import main
  File "/usr/local/lib/python3.4/dist-packages/miio/__init__.py", line 2, in <module>
    from miio.airconditioningcompanion import AirConditioningCompanion
  File "/usr/local/lib/python3.4/dist-packages/miio/airconditioningcompanion.py", line 7, in <module>
    from .click_common import command, format_output, EnumType
  File "/usr/local/lib/python3.4/dist-packages/miio/click_common.py", line 9, in <module>
    sys.version_info)
TypeError: not all arguments converted during string formatting
```

Any idea how to resolve this?

**Comment by rytilahti** [comment] 2018-10-08 20:52
You have to use python 3.5 or newer. However, the error should be fixed, too. The error is caused by the fact that `sys.version_info` is a tuple, but the format string has just a single placeholder in place.

**Comment by salcabo** [comment] 2018-10-31 11:18
I have the same problem, unistalled python 2.7 and cheked version 3.5 is running. 

I must say I'm totaly new

**Closed** 2018-10-31 11:37 UTC

**Comment by rytilahti** [comment] 2018-10-31 11:38
What is the full stack trace? In original reporter's case that was 3.4 as can be seen from the stack trace, version 3.5 should be fine.
