### ISSUE TITLE
mirobo status throws errors

### ISSUE THREAD

**Issue by binford6000** [rytilahti/python-miio#1206] opened 2021-12-02 18:49 UTC
Hi there,
when executing following command
`mirobo --ip 192.168.8.1 --token <token> status`

the following error comes up:

Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/miio/click_common.py", line 59, in __ call __
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/miio/integrations/vacuum/roborock/vacuum_cli.py", line 72, in cli
    vac = RoborockVacuum(ip, token, start_id, debug)
UnboundLocalError: local variable 'start_id' referenced before assignment

**Version information:**
 - OS: `Linux raspberrypi 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux` 
 - `debian bullseye`
 - python-miio: `mirobo, version 0.5.9.1`

Greets,
Sebastian

**Comment by rytilahti** [comment] 2021-12-02 19:40
Hi Sebastian, this is duplicate of #1205, looks like some recent change broke the id file handling. For the time being you could simply create that file manually, the default location is `$HOME/.cache/python-miio/python-mirobo.seq` and the content would be `{}` to make it parse as a JSON.

**Closed by rytilahti** 2021-12-02 19:40 UTC
Labels: bug

**Comment by binford6000** [comment] 2021-12-03 13:17
Hi,
thx for the help. Creating the file maually worked for me! 
But now i am running into #1103 
My vac is brandnew - seems that the fimrware is too new like you mentioned in your last comment over there.
Is there any chance of downgrading?
Greets,
Sebastian

**Comment by rytilahti** [comment] 2021-12-04 23:07
Alas, I don't know any easy ways for downgrading the firmware if the factory one is blocking updates. You may want to check out [dustcloud community](https://github.com/dgiese/dustcloud/), maybe someone there has figured it out :-)

**Comment by binford6000** [comment] 2021-12-05 09:37
> Alas, I don't know any easy ways for downgrading the firmware if the factory one is blocking updates. You may want to check out [dustcloud community](https://github.com/dgiese/dustcloud/), maybe someone there has figured it out :-)

Hi,
yes, there was the answer: My vac is too new so ota is not longer possible with recovery firmware. I have to go the long way...
Thx! :-)

**Comment by asmaps** [comment] 2021-12-13 10:07
> Hi, yes, there was the answer: My vac is too new so ota is not longer possible with recovery firmware. I have to go the long way... Thx! :-)

Hey, I got exactly the same problem and I can't find a tutorial for the "long way". Which way did you take? Did it work?

**Comment by asdil12** [comment] 2022-01-17 19:20
Hi,
I'm running into the same issue. Could you maybe give me a hint what to do here?
